`timescale 1ns/1ps

module tb_cpu;

    reg clk;
    reg rst;

    // Instantiate the full CPU
    cpu uut (
        .clk(clk),
        .rst(rst)
    );

    always #5 clk = ~clk;

    initial begin
        $dumpfile("wave_cpu.vcd");
        $dumpvars(0, tb_cpu);

        // 1. LOAD THE COMPILED C PROGRAM!
        // We are using a Verilog system task to read the hex file generated by the GCC compiler.
        $readmemh("software/program.hex", uut.imem.mem);

        // Reset the CPU
        clk = 0;
        rst = 1;
        #15;
        rst = 0;

        // Wait for the program to execute all 6 instructions
        #60; 

        // Verify the C Program results
        $display("--- CPU RUNNING C CODE VERIFICATION ---");
        
        // GCC mapped the 'a+b' result (15) to register a5 (x15)
        if (uut.rf.regs[15] !== 32'd15) $display("FAIL: a5 (x15) did not equal 15");
        else $display("PASS: Register a5 successfully loaded 15");
        
        // GCC stored the result to memory address 252. 
        // 252 / 4 = index 63 in our Data Memory array.
        if (uut.dmem.mem[63] !== 32'd15) $display("FAIL: RAM[252] did not equal 15");
        else $display("PASS: C Pointer successfully wrote 15 to RAM address 252");
        
        #20;
        // Check if the infinite loop (while(1)) is trapping the PC
        if (uut.PC == 32'd8) $display("PASS: 'while(1)' loop successfully trapped the PC!");
        else $display("FAIL: CPU escaped the infinite loop. PC is %d", uut.PC);

        $display("ALL CPU TESTS COMPLETED!");
        $finish;
    end

endmodule
